version: '3.8'
services:
  discovery:
    image: discovery-service
    ports:
      - 10002:10002
  gateway:
    image: gateway-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:10002/eureka
    depends_on:
      - discovery
    ports:
      - 10003:10003
  account-service:
    image: account-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:10002/eureka
    depends_on:
      - discovery
