name: CI/CD
on: push
env:
  ECR_REPOSITORY_PREFIX: ${{ secrets.ECR_REPOSITORY_PREFIX }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PREFIX }}-${{ secrets.APP_NAME }}
  IMAGE_TAG: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  PROJECT_ROOT: rss-gateway-service
jobs:
  sonar_maven_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven and Sonar
        run: |
         cd ./$PROJECT_ROOT ;we will CD to ./project_root if we have package_root/project_root structure
          ls
          mvn verify sonar:sonar -Dsonar.projectKey=201026java_$APP_NAME-service -Dsonar.organization=201026java -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
      # ---[ Configuring AWS credentials and Logging in to ECR ]---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
     # - name: Checkout
     #   uses: actions/checkout@v2
      - name: Build the image
        id: docker_build
        run: |
          pwd
          ls
          cd ./PROJECT_ROOT ;we will CD to ./project_root if we have package_root/project_root structure 
					;note that obtaining the jar artifact is from within the Dockerfile
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
  deploy: 
    # ---[ Use docker image from the build step and deploy on EKS ]---
    needs: [sonar_maven_build]
    name: Deploy on EKS
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EKS
        run: |
          aws configure set aws_access_key_id ${{ secrets.EKS_ACCESS_KEY_ID }} --profile p3
          aws configure set aws_secret_access_key ${{ secrets.EKS_SECRET_ACCESS_KEY }} --profile p3
          aws configure set default.region ${{ secrets.AWS_REGION }} --profile p3
          aws eks --region us-east-1 update-kubeconfig --profile p3 --name $ECR_REPOSITORY_PREFIX 
          kubectl --namespace default set image deploy/${{secrets.APP_NAME}}-service-deployment ${{secrets.APP_NAME}}-service=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          kubectl --namespace default rollout status deploy/${{secrets.APP_NAME}}-service-deployment
